name: visual_ia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1 
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  http: ^1.2.2
  convert: ^3.1.1
  flutter_gemini: ^2.0.4
  google_generative_ai: ^0.4.4
  google_gemini: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
